### ISSUE TITLE
INFO/END is smaller than POS

### ISSUE THREAD

**Issue by linsindian** [KolmogorovLab/Severus#11]
Hi @aysegokce ,

I'm currently trying to replicate your testing on COLO829 using the COLO829 nanopore data provided by epi2me labs. 
The workflow likes: `Clair3 -> whatshap phasing and tagging -> severus call SV -> truvari bench`.

However, I encountered an error while attempting to index severus_somatic.vcf using bcftools: 
`[W::tbx_parse1] VCF INFO/END=10003 is smaller than POS at chr1:180575`. 
It seems that this issue stems from the possibility of encountering END being smaller than POS when SVtype is BND.

Could you please explain how you operate `Truvari` as a benchmarking tool?

Best,
Sin-Dian

**Comment by aysegokce** [comment]
Hello @linsindian,

Truvari only works with sequence-resolved SVs like INDELs and cannot handle BNDs. Since SVs in the cancer genome are BNDs in major, we couldn't find a tool that can handle different representations. We developed Minda, optimized for cancer data and agnostic to SV types, to merge and compare VCFs. It will be available soon.

In the vcf format, BND calls need to be duplicated as a-to-b and b-to-a, and in the b-to-a row, END will be smaller than the POS.

Best
Ayse

**Comment by TBradley27** [comment]
Hello @aysegokce,

I was wondering whether your comments are also applicable to SVs of type INV?

We got the following error with Snpeff:

![image](https://github.com/KolmogorovLab/Severus/assets/13511784/df1d66bc-ebf1-43ee-ad9f-652f280478ef)
