### ISSUE TITLE
Phasing with tumour-only long-reads as input for severus

### ISSUE THREAD

**Issue by eesiribloom** [KolmogorovLab/Severus#18]
I have nanopore long-reads from tumor (tumor only)
I also have SNP/indel variant calls from the same sample from illumina in both germline (normal) and tumor data

I want to try and phase the tumour bam so I can use severus to detect complex rearrangements. 

as such, which input.vcf should I use to accompany my tumor.bam for phasing for best results with severus?
a) illumina SNP/indel calls from normal
b) illumina SNP/indel calls from tumor
I could also generate c) nanopore SNP/indel calls from tumor

**Comment by aysegokce** [comment]
Hello,
For Severus, we need phased vcfs + haplotagged bams.
Since you have germline calls from Illumina, I suggest you phase normal calls (Illumina) with whatshap and then haplotagging tumor bam with that vcf. Alternatively, you can directly phase nanopore tumor calls using Clair3 and then haplotag.  We have a command line for these tools [here](https://github.com/KolmogorovLab/Severus?tab=readme-ov-file#preparing-phased-and-haplotagged-alignments) 

For phasing using whatshap (Illumina normal):
`whatshap phase -o phased.vcf --reference=reference.fasta input.vcf tumor.bam `

Best
Ayse
