### ISSUE TITLE
Haptype information in output files

### ISSUE THREAD

**Issue by ywzhang071394** [KolmogorovLab/Severus#24]
Hi,

Severus is fantastic and very helpful for my current study. In particular, the complex SVs were visualized in a convient way.
However, I still has several questions about the output files and hope you can give a brief explanation.

1. As shown in the below figure, there is a label for the interactive breakends. I was confused about the meaning of "Haplotype 2|1". I feel it was used to characterize Hom and Het. Does "2" stand for Hap2, "1" stand for Hap1, and "0" stand for both Haps?

![image](https://github.com/user-attachments/assets/46c01397-a4dd-4345-b4ba-040592d859e5)

2. I saw some items in the VCF file have no HP tag. Does it mean that they are not well phased or they present in both haploids?

Thanks!

**Comment by aysegokce** [comment]
Hello @ywzhang071394,

We use HP=0 as breakpoints only supported by unphased reads. In this example, breakpoint 1 is in haplotype 2, and breakpoint 2 is in haplotype 1. If an SV is supported by both haplotypes, which rarely happens in somatic cases and is often associated with phasing issues, we represent them as homozygous in `breakpoint_clusters. tsv`. 

In the vcf, we provide haplotype-specific VAF (`hVAF`) for each haplotype. We use the HP tag only with SVs supported by a single haplotype. If there is no HP tag, either it is supported by unphased reads, or both haplotypes support it. These cases are often associated with phasing issues, so we avoid coming to a conclusion.

We don't combine edges with different haplotypes in the graphs because they may have different genomic segment connections.  

Best
Ayse

**Comment by ywzhang071394** [comment]
Thank you Ayse.
Very helpful and timely!
I would close this issue.
