### ISSUE TITLE
converting insertions to translocations

### ISSUE THREAD

**Issue by eesiribloom** [KolmogorovLab/Severus#32]
Please could you provide more detail on the parameter `--ins-to-tra`?
When would you recommend using this parameter and why?

**Comment by aysegokce** [comment]
Hello,

In alignments, the same event can be represented as an aligned insertion (as purple I in IGV) or as a split alignment to where the sequence is aligned, as in the IGV screenshot below. We can represent this as an insertion or translocation in the vcf. `--ins-to-tra `controls this. The default is to uniform it as an insertion and provide an insertion sequence and the `ALINGED_POS `field in the INFO column. 

It was helpful in earlier versions. Currently, I don't recommend using it since we also provide aligned position. 

Best
Ayse

<img width="1276" alt="Screenshot 2024-11-11 at 12 58 53 PM" src="https://github.com/user-attachments/assets/cc3a2470-dffc-4abe-b5ba-a9bfb8333f5f">
